/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.GridLayout;
import java.util.ArrayList;
import model.DonModel;
import model.UserModel;

/**
 *
 * @author Extreme
 */
public class ReqTableRow extends javax.swing.JPanel {

    /**
     * Creates new form ReqTableRow
     */
    public ReqTableRow(DonModel donModel, ArrayList<UserModel> reqs) {
        initComponents();
        DonPanel donPanel = new DonPanel(donModel);
        donPanel.setOpaque(false);
        donPanel.setBorder(null);
        donPan.add(donPanel);
        ((GridLayout)donPan.getLayout()).setRows(reqs.size());
        ((GridLayout)reqPan.getLayout()).setRows(reqs.size());
        for (UserModel req : reqs) {
            reqPan.add(new ReqUserPanel(donModel, req, this));
        }
        
        donPan.repaint();
        donPan.validate();
        
        reqPan.repaint();
        reqPan.validate();
        
        setSize(680, 100*reqs.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chLb = new javax.swing.JLabel();
        donPan = new javax.swing.JPanel();
        reqPan = new javax.swing.JPanel();

        chLb.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        chLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chLb.setText("Choosen");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        donPan.setBackground(new java.awt.Color(255, 255, 255));
        donPan.setLayout(new java.awt.GridLayout(1, 1));

        reqPan.setBackground(new java.awt.Color(255, 255, 255));
        reqPan.setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(donPan, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(reqPan, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reqPan, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(donPan, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chLb;
    private javax.swing.JPanel donPan;
    private javax.swing.JPanel reqPan;
    // End of variables declaration//GEN-END:variables
    public void choosen(){
        reqPan.removeAll();
    }
}
