/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import com.vcodes.vimage.image.ImageHandler;
import controller.DonControllerImpl;
import controller.UserControllerImpl;
import java.awt.GridLayout;
import java.io.IOException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.DonModel;
import model.UserModel;

/**
 *
 * @author Extreme
 */
public class ViewUser extends javax.swing.JFrame {
    private static UserControllerImpl userControllerImpl;
    private static DonControllerImpl donControllerImpl;
    
    static {
        try {
            userControllerImpl = new UserControllerImpl();
            donControllerImpl = new DonControllerImpl();
        } catch (RemoteException ex) {
            Logger.getLogger(ViewUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * Creates new form ViewUser
     */
    public ViewUser(String nic) {
        initComponents();
        setLocationRelativeTo(null);
        try {
            UserModel user = userControllerImpl.getUser(nic);
            profPicLb5.setIcon(ImageHandler.scaleToSpace(user.getProfpic(), 168, 156));
            fNameTx.setText(user.getfName());
            lNameTx.setText(user.getlName());
            nicTx.setText(user.getNic());
            tpTx.setText(Integer.toString(user.getTp()));
            mailTx.setText(user.getMail());
            addressTx.setText(user.getAddress());
            
            ArrayList<DonModel> donations = donControllerImpl.getDonation(nic);
            if (donations.size() > 0) {
                ((GridLayout)donPan.getLayout()).setRows(donations.size());
                donPan.setSize(350, 100*donations.size());
                for (DonModel dModel : donations) {
                    donPan.add(new DonPanel(dModel));
                }
                donPan.repaint();
                donPan.validate();
                noDonLb.setVisible(false);
            }else{
                noDonLb.setVisible(true);
            }
            
            ArrayList<DonModel> reqDoantions = donControllerImpl.getReqDoantions(nic);
            if (reqDoantions.size() > 0) {
                ((GridLayout)reqPan.getLayout()).setRows(reqDoantions.size());
                reqPan.setSize(350, 100*reqDoantions.size());
                for (DonModel dModel : reqDoantions) {
                    reqPan.add(new DonPanel(dModel));
                }
                reqPan.repaint();
                reqPan.validate();
                noReqLb.setVisible(false);
                
            }else{
                noReqLb.setVisible(true);
            }
            
        } catch (RemoteException ex) {
            Logger.getLogger(ViewUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ViewUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ViewUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ViewUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        profPicLb5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fNameTx = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lNameTx = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nicTx = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tpTx = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mailTx = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addressTx = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        donContainer = new javax.swing.JPanel();
        noDonLb = new javax.swing.JLabel();
        donPan = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        reqContainer = new javax.swing.JPanel();
        noReqLb = new javax.swing.JLabel();
        reqPan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setText("User Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Profile Picture"), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N

        profPicLb5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profPicLb5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profPicLb5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profPicLb5, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profPicLb5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel2.setText("First Name : ");

        fNameTx.setEditable(false);
        fNameTx.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        fNameTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fNameTxKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel3.setText("NIC Number :");

        lNameTx.setEditable(false);
        lNameTx.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lNameTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lNameTxKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel4.setText("TP Number :");

        nicTx.setEditable(false);
        nicTx.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        nicTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicTxKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel5.setText("E-mail :");

        tpTx.setEditable(false);
        tpTx.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        tpTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpTxKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel6.setText("Address :");

        mailTx.setEditable(false);
        mailTx.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        mailTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mailTxKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel7.setText("Last Name :");

        addressTx.setEditable(false);
        addressTx.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        addressTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressTxKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(104, 104, 104)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressTx)
                    .addComponent(mailTx)
                    .addComponent(tpTx)
                    .addComponent(nicTx)
                    .addComponent(lNameTx)
                    .addComponent(fNameTx))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fNameTx, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lNameTx, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nicTx, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tpTx, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailTx, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressTx, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Donations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 12))); // NOI18N

        donContainer.setBackground(new java.awt.Color(255, 255, 255));
        donContainer.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                donContainerMouseWheelMoved(evt);
            }
        });
        donContainer.setLayout(null);

        noDonLb.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        noDonLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noDonLb.setText("No Donations");
        donContainer.add(noDonLb);
        noDonLb.setBounds(0, 0, 350, 100);

        donPan.setBackground(new java.awt.Color(255, 255, 255));
        donPan.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                donPanMouseWheelMoved(evt);
            }
        });
        donPan.setLayout(new java.awt.GridLayout(1, 1));
        donContainer.add(donPan);
        donPan.setBounds(0, 0, 350, 100);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(donContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(donContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Requests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 12))); // NOI18N

        reqContainer.setBackground(new java.awt.Color(255, 255, 255));
        reqContainer.setLayout(null);

        noReqLb.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        noReqLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noReqLb.setText("No Requests");
        reqContainer.add(noReqLb);
        noReqLb.setBounds(0, 0, 350, 100);

        reqPan.setBackground(new java.awt.Color(255, 255, 255));
        reqPan.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                reqPanMouseWheelMoved(evt);
            }
        });
        reqPan.setLayout(new java.awt.GridLayout(1, 1));
        reqContainer.add(reqPan);
        reqPan.setBounds(0, 0, 350, 100);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reqContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reqContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profPicLb5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profPicLb5MouseClicked
        
    }//GEN-LAST:event_profPicLb5MouseClicked

    private void fNameTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameTxKeyReleased
        
    }//GEN-LAST:event_fNameTxKeyReleased

    private void lNameTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNameTxKeyReleased
        
    }//GEN-LAST:event_lNameTxKeyReleased

    private void nicTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicTxKeyReleased
        
    }//GEN-LAST:event_nicTxKeyReleased

    private void tpTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpTxKeyReleased
        
    }//GEN-LAST:event_tpTxKeyReleased

    private void mailTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailTxKeyReleased
        
    }//GEN-LAST:event_mailTxKeyReleased

    private void addressTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTxKeyReleased
        

    }//GEN-LAST:event_addressTxKeyReleased

    private void donContainerMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_donContainerMouseWheelMoved
        
    }//GEN-LAST:event_donContainerMouseWheelMoved

    private void donPanMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_donPanMouseWheelMoved
        if (evt.getWheelRotation() > 0 && donPan.getY()+donPan.getHeight() > donContainer.getHeight()) {
            donPan.setLocation(0, donPan.getY()-100);
        }else if (evt.getWheelRotation() < 0 && donPan.getY() < 0) {
            donPan.setLocation(0, donPan.getY() + 100);
        }
    }//GEN-LAST:event_donPanMouseWheelMoved

    private void reqPanMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_reqPanMouseWheelMoved
        if (evt.getWheelRotation() > 0 && reqPan.getY()+reqPan.getHeight() > reqContainer.getHeight()) {
            reqPan.setLocation(0, reqPan.getY()-100);
        }else if (evt.getWheelRotation() < 0 && reqPan.getY() < 0) {
            reqPan.setLocation(0, reqPan.getY() + 100);
        }
    }//GEN-LAST:event_reqPanMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
            //</editor-fold>
            
            UIManager.setLookAndFeel(new GraphiteLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ViewUser.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUser("952050826V").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTx;
    private javax.swing.JPanel donContainer;
    private javax.swing.JPanel donPan;
    private javax.swing.JTextField fNameTx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField lNameTx;
    private javax.swing.JTextField mailTx;
    private javax.swing.JTextField nicTx;
    private javax.swing.JLabel noDonLb;
    private javax.swing.JLabel noReqLb;
    private javax.swing.JLabel profPicLb5;
    private javax.swing.JPanel reqContainer;
    private javax.swing.JPanel reqPan;
    private javax.swing.JTextField tpTx;
    // End of variables declaration//GEN-END:variables
}
