/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.vcodes.vimage.image.ImageHandler;
import connector.ServerConnector;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.DonModel;
import model.UserModel;

/**
 *
 * @author Extreme
 */
public class AvaDonPanel extends javax.swing.JPanel {
    private DonModel donModel;
    private String userNic;
    private Home home;
    /**
     * Creates new form AvaDonPanel
     */
    public AvaDonPanel(DonModel donModel, String userNic, Home home) {
        initComponents();
        picLb.setIcon(ImageHandler.scaleToSpace(donModel.getImg(), 128, 128));
        donLb.setText(donModel.getDonation());
        descTx.setText(donModel.getDesc());
        this.donModel = donModel;
        this.userNic = userNic;
        this.home = home;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picLb = new javax.swing.JLabel();
        donLb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descTx = new javax.swing.JTextArea();
        reqBt = new javax.swing.JButton();
        viewBt = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        donLb.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        donLb.setText("jLabel1");

        descTx.setEditable(false);
        descTx.setColumns(20);
        descTx.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        descTx.setRows(5);
        jScrollPane1.setViewportView(descTx);

        reqBt.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        reqBt.setText("Request");
        reqBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqBtActionPerformed(evt);
            }
        });

        viewBt.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        viewBt.setText("View Details");
        viewBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picLb, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(donLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reqBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewBt, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(donLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reqBt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewBt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(picLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtActionPerformed
        try {
            UserModel user = ServerConnector.getServerConnector().getUserController().getUser(donModel.getDonar());
            new DonationDetail(donModel, user, "Donar Details").setVisible(true);
        } catch (NotBoundException ex) {
            Logger.getLogger(AvaDonPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(AvaDonPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(AvaDonPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AvaDonPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AvaDonPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AvaDonPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewBtActionPerformed

    private void reqBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqBtActionPerformed
        try {
            boolean requestDonation = ServerConnector.getServerConnector().getDonController().requestDonation(donModel.getDonId(), userNic);
            if (requestDonation) {
                JOptionPane.showMessageDialog(this, "Request Sent...", "", JOptionPane.INFORMATION_MESSAGE);
                home.update();
            }else{
                JOptionPane.showMessageDialog(this, "Couldn't request...", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(AvaDonPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(AvaDonPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(AvaDonPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AvaDonPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AvaDonPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AvaDonPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reqBtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descTx;
    private javax.swing.JLabel donLb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel picLb;
    private javax.swing.JButton reqBt;
    private javax.swing.JButton viewBt;
    // End of variables declaration//GEN-END:variables
}
