/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.vcodes.vimage.image.ImageHandler;
import connector.ServerConnector;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.DonModel;
import model.UserModel;

/**
 *
 * @author Extreme
 */
public class MyDonPanel extends javax.swing.JPanel {
    DonModel donModel;
    private UserModel user;
    /**
     * Creates new form MyDonPanel
     */
    public MyDonPanel(DonModel donModel) {
        initComponents();
        this.donModel = donModel;
        donLb.setText(donModel.getDonation());
        picLb.setIcon(ImageHandler.scaleToSpace(donModel.getImg(), 100, 100));
        if (donModel.getRecipient().equals("")) {
            pendingLb.setVisible(true);
            profPicLb.setVisible(false);
            nameTx.setVisible(false);
            mailTx.setVisible(false);
            viewBt.setVisible(false);
        }else{
            try {
                user = ServerConnector.getServerConnector().getUserController().getUser(donModel.getRecipient());
                profPicLb.setIcon(ImageHandler.scaleToSpace(user.getProfpic(), 100, 100));
                nameTx.setText(user.getfName() + " " + user.getlName());
                mailTx.setText(user.getMail());
                pendingLb.setVisible(false);
                profPicLb.setVisible(true);
                nameTx.setVisible(true);
                mailTx.setVisible(true);
                viewBt.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(MyDonPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MyDonPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MyDonPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(MyDonPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donLb = new javax.swing.JLabel();
        picLb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        donLb1 = new javax.swing.JLabel();
        profPicLb = new javax.swing.JLabel();
        mailTx = new javax.swing.JLabel();
        pendingLb = new javax.swing.JLabel();
        nameTx = new javax.swing.JLabel();
        viewBt = new javax.swing.JButton();
        donLb4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        donLb.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        donLb.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        donLb1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jPanel1.add(donLb1);
        donLb1.setBounds(120, 30, 260, 0);
        jPanel1.add(profPicLb);
        profPicLb.setBounds(0, 25, 100, 100);

        mailTx.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        mailTx.setText("Recipient : ");
        jPanel1.add(mailTx);
        mailTx.setBounds(130, 50, 290, 20);

        pendingLb.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        pendingLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingLb.setText("Pending...");
        jPanel1.add(pendingLb);
        pendingLb.setBounds(90, 30, 190, 60);

        nameTx.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        nameTx.setText("Recipient : ");
        jPanel1.add(nameTx);
        nameTx.setBounds(130, 20, 290, 20);

        viewBt.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        viewBt.setText("View Recipient Details");
        viewBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtActionPerformed(evt);
            }
        });
        jPanel1.add(viewBt);
        viewBt.setBounds(130, 83, 290, 30);

        donLb4.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        donLb4.setText("Recipient : ");
        jPanel1.add(donLb4);
        donLb4.setBounds(0, 0, 70, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(donLb, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picLb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(donLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picLb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtActionPerformed
        new DonationDetail(donModel, user, "Recipient Details").setVisible(true);
    }//GEN-LAST:event_viewBtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel donLb;
    private javax.swing.JLabel donLb1;
    private javax.swing.JLabel donLb4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mailTx;
    private javax.swing.JLabel nameTx;
    private javax.swing.JLabel pendingLb;
    private javax.swing.JLabel picLb;
    private javax.swing.JLabel profPicLb;
    private javax.swing.JButton viewBt;
    // End of variables declaration//GEN-END:variables
}
