/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.vcodes.vimage.image.ImageHandler;
import connector.ServerConnector;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.DonModel;
import model.UserModel;

/**
 *
 * @author Extreme
 */
public class MyReqPanel extends javax.swing.JPanel {
    private DonModel donModel;
    private String userNic;
    private Home home;
    /**
     * Creates new form MyReqPanel
     */
    private  MyReqPanel() {
        initComponents();
    }
    
    public MyReqPanel(DonModel donModel, String userNic, Home home){
        this();
        this.donModel = donModel;
        this.userNic = userNic;
        this.home = home;
        picLb.setIcon(ImageHandler.scaleToSpace(donModel.getImg(), 128, 128));
        donLb.setText(donModel.getDonation());
        descTx.setText(donModel.getDesc());
        String recipient = donModel.getRecipient();
        if (recipient.equals("")) {
            stateLb.setVisible(false);
            canReqBt.setVisible(true);
        }else if (recipient.equals(userNic)) {
            canReqBt.setVisible(false);
            stateLb.setVisible(true);
            stateLb.setText("<html>You are choosen</Br>for this donation</html>");
        }else{
            canReqBt.setVisible(false);
            stateLb.setVisible(true);
            stateLb.setText("<html>You are not</Br>choosen<Br>for this donation</html>");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        canReqBt = new javax.swing.JButton();
        stateLb = new javax.swing.JLabel();
        picLb = new javax.swing.JLabel();
        donLb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descTx = new javax.swing.JTextArea();
        viewBt = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        canReqBt.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        canReqBt.setText("Cancel Request");
        canReqBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canReqBtActionPerformed(evt);
            }
        });
        jPanel1.add(canReqBt);
        canReqBt.setBounds(0, 12, 123, 36);

        stateLb.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        stateLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stateLb.setText("You are Choosen");
        jPanel1.add(stateLb);
        stateLb.setBounds(0, 0, 120, 80);

        donLb.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        donLb.setText("jLabel1");

        descTx.setEditable(false);
        descTx.setColumns(20);
        descTx.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        descTx.setRows(5);
        jScrollPane1.setViewportView(descTx);

        viewBt.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        viewBt.setText("View Details");
        viewBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picLb, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(donLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewBt, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(picLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(donLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewBt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtActionPerformed
        try {
            UserModel user = ServerConnector.getServerConnector().getUserController().getUser(donModel.getDonar());
            new DonationDetail(donModel, user, "Donar Details").setVisible(true);
        } catch (NotBoundException ex) {
            Logger.getLogger(MyReqPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(MyReqPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(MyReqPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MyReqPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MyReqPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MyReqPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewBtActionPerformed

    private void canReqBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canReqBtActionPerformed
        try {
            boolean cancelRequest = ServerConnector.getServerConnector().getDonController().cancelRequest(donModel.getDonId(), userNic);
            if (cancelRequest) {
                JOptionPane.showMessageDialog(this, "Request Canceled...", "", JOptionPane.INFORMATION_MESSAGE);
                home.update();
            }else{
                JOptionPane.showMessageDialog(this, "Couldn't Cancel", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(MyReqPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(MyReqPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(MyReqPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MyReqPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MyReqPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MyReqPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_canReqBtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canReqBt;
    private javax.swing.JTextArea descTx;
    private javax.swing.JLabel donLb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel picLb;
    private javax.swing.JLabel stateLb;
    private javax.swing.JButton viewBt;
    // End of variables declaration//GEN-END:variables
}
