/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import com.vcodes.vimage.image.ImageHandler;
import connector.ServerConnector;
import controller.UserController;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.UserModel;
import other.Email;
import other.Validation;

/**
 *
 * @author Extreme
 */
public class UserAccount extends javax.swing.JFrame {
    private ImageIcon profPic;
    private final static Email EMAIL = new Email();

    /**
     * Creates new form NewUser
     */
    public UserAccount() {
        
        initComponents();
        setLocationRelativeTo(null);
        updateBt.setVisible(false);
        
    }
    
    public UserAccount(UserModel userModel){
        this();
        fNameTx.setText(userModel.getfName());
        lNameTx.setText(userModel.getlName());
        nicTx.setText(userModel.getNic());
        tpTx.setText("0"+Integer.toString(userModel.getTp()));
        mailTx.setText(userModel.getMail());
        addressTx.setText(userModel.getAddress());
        pwTx.setText(userModel.getPassword());
        conPwTx.setText(userModel.getPassword());
        profPic = userModel.getProfpic();
        profPicLb.setIcon(ImageHandler.scaleToSpace(profPic, 250, 250));
        nicTx.setEditable(false);
        createBt.setVisible(false);
        updateBt.setVisible(true);
        headerTx.setText("Account Settings");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        headerTx = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        profPicLb = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fNameTx = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lNameTx = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nicTx = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tpTx = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mailTx = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addressTx = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pwTx = new javax.swing.JPasswordField();
        conPwTx = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        createBt = new javax.swing.JButton();
        updateBt = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        headerTx.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        headerTx.setText("New Account");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerTx)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerTx)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Profile Picture"), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N

        profPicLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profPicLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/noProfPic.png"))); // NOI18N
        profPicLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profPicLbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profPicLb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profPicLb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setText("First Name : ");

        fNameTx.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        fNameTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fNameTxKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setText("Last Name : ");

        lNameTx.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lNameTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lNameTxKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setText("NIC number : ");

        nicTx.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        nicTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicTxKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setText("TP number : ");

        tpTx.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        tpTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpTxKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setText("E-mail : ");

        mailTx.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        mailTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mailTxKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setText("Address :");

        addressTx.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        addressTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressTxKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mailTx)
                    .addComponent(tpTx)
                    .addComponent(nicTx)
                    .addComponent(lNameTx)
                    .addComponent(fNameTx)
                    .addComponent(addressTx, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fNameTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lNameTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nicTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tpTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(mailTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(addressTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Privercy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel10.setText("Password : ");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel11.setText("Confirm Password : ");

        pwTx.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        pwTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwTxKeyReleased(evt);
            }
        });

        conPwTx.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        conPwTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                conPwTxKeyReleased(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        createBt.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        createBt.setText("Create Account");
        createBt.setEnabled(false);
        createBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtActionPerformed(evt);
            }
        });
        jPanel5.add(createBt);
        createBt.setBounds(10, 0, 243, 68);

        updateBt.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        updateBt.setText("Update");
        updateBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtActionPerformed(evt);
            }
        });
        jPanel5.add(updateBt);
        updateBt.setBounds(10, 0, 243, 68);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwTx, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conPwTx, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(pwTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(conPwTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profPicLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profPicLbMouseClicked
        try {
            profPic = ImageHandler.importImage();
            if (profPic != null) {
                ImageIcon scaleImage = ImageHandler.scaleToSpace(profPic, 250, 250);
                profPicLb.setIcon(scaleImage);
            }
            enableCreateUpdateBtns();
        } catch (IOException ex) {
            Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Please insert an image", "Error",  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_profPicLbMouseClicked

    private void createBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtActionPerformed
        if(nicTx.getText().length() < 10){
            JOptionPane.showMessageDialog(this, "There should be 9 numbers and one character in NIC number...", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(tpTx.getText().length() < 10){
            JOptionPane.showMessageDialog(this, "There should be 10 numbers in TP number...", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(!Validation.isMailValid(mailTx.getText())){
            JOptionPane.showMessageDialog(this, "Please Enter a valid Email...", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(!passwordMatches()){
            JOptionPane.showMessageDialog(this, "Passwor and its confirmation is not matched...", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                UserController userController = ServerConnector.getServerConnector().getUserController();
                boolean addNewUser = userController.addNewUser(new UserModel(fNameTx.getText(), lNameTx.getText(), nicTx.getText(), Integer.parseInt(tpTx.getText()), mailTx.getText(), addressTx.getText(), new String(pwTx.getPassword()), profPic));
                if(addNewUser){
                    JOptionPane.showMessageDialog(this, "Account Created Successfully...", "", JOptionPane.INFORMATION_MESSAGE);
                    new Thread(){

                        @Override
                        public void run() {
                            try {
                                EMAIL.send(mailTx.getText(), "Welcome to WECare", "Congratulations! You've registered an account successfully.Thank you for joining us!\n" +
"Now you can Donate, View other donates and request fro them through WECare.");
                            } catch (MessagingException ex) {
                                Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        
                    }.start();
                }else{
                    JOptionPane.showMessageDialog(this, "Couldn't Create the Account...", "", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NotBoundException ex) {
                Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MalformedURLException ex) {
                Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RemoteException ex) {
                Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            clearAll();
            dispose();
        }
    }//GEN-LAST:event_createBtActionPerformed

    private void nicTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicTxKeyReleased
        Validation.validateNIC(nicTx);
        enableCreateUpdateBtns();
    }//GEN-LAST:event_nicTxKeyReleased

    private void tpTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpTxKeyReleased
        Validation.validateTelNo(tpTx);
        enableCreateUpdateBtns();
    }//GEN-LAST:event_tpTxKeyReleased

    private void fNameTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameTxKeyReleased
        Validation.stringsOnly(fNameTx);
        Validation.limitCharacterCount(fNameTx, 20);
        enableCreateUpdateBtns();
    }//GEN-LAST:event_fNameTxKeyReleased

    private void lNameTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNameTxKeyReleased
        Validation.stringsOnly(lNameTx);
        Validation.limitCharacterCount(lNameTx, 20);
        enableCreateUpdateBtns();
    }//GEN-LAST:event_lNameTxKeyReleased

    private void mailTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailTxKeyReleased
        Validation.noSpace(mailTx);
        Validation.limitCharacterCount(mailTx, 50);
        enableCreateUpdateBtns();
    }//GEN-LAST:event_mailTxKeyReleased

    private void addressTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTxKeyReleased
        Validation.limitCharacterCount(addressTx, 50);
        enableCreateUpdateBtns();
        
    }//GEN-LAST:event_addressTxKeyReleased

    private void pwTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwTxKeyReleased
        Validation.limitCharacterCount(pwTx, 15);
        enableCreateUpdateBtns();
    }//GEN-LAST:event_pwTxKeyReleased

    private void conPwTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conPwTxKeyReleased
        Validation.limitCharacterCount(conPwTx, 15);
        enableCreateUpdateBtns();
    }//GEN-LAST:event_conPwTxKeyReleased

    private void updateBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtActionPerformed
        if(tpTx.getText().length() < 10){
            JOptionPane.showMessageDialog(this, "There should be 10 numbers in TP number...", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(!Validation.isMailValid(mailTx.getText())){
            JOptionPane.showMessageDialog(this, "Please Enter a valid Email...", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(!passwordMatches()){
            JOptionPane.showMessageDialog(this, "Passwor and its confirmation is not matched...", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                UserController userController = ServerConnector.getServerConnector().getUserController();
                boolean update = userController.updateUser(new UserModel(fNameTx.getText(), lNameTx.getText(), nicTx.getText(), Integer.parseInt(tpTx.getText()), mailTx.getText(), addressTx.getText(), new String(pwTx.getPassword()), profPic));
                if(update){
                    JOptionPane.showMessageDialog(this, "Account Updated Successfully...", "", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, "Couldn't update the Account...", "", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NotBoundException ex) {
                Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MalformedURLException ex) {
                Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RemoteException ex) {
                Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            dispose();
        }
    }//GEN-LAST:event_updateBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
            //</editor-fold>
            
            /* Create and display the form */
        try {
            UIManager.setLookAndFeel(new GraphiteLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTx;
    private javax.swing.JPasswordField conPwTx;
    private javax.swing.JButton createBt;
    private javax.swing.JTextField fNameTx;
    private javax.swing.JLabel headerTx;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField lNameTx;
    private javax.swing.JTextField mailTx;
    private javax.swing.JTextField nicTx;
    private javax.swing.JLabel profPicLb;
    private javax.swing.JPasswordField pwTx;
    private javax.swing.JTextField tpTx;
    private javax.swing.JButton updateBt;
    // End of variables declaration//GEN-END:variables
    
    
    void enableCreateUpdateBtns(){
        boolean enable = fNameTx.getText().length()>0 && lNameTx.getText().length()>0 && nicTx.getText().length()>0 && tpTx.getText().length()>0 &&  mailTx.getText().length()>0 && addressTx.getText().length()>0 && pwTx.getPassword().length>0 && conPwTx.getPassword().length>0 && profPic != null;
        createBt.setEnabled(enable);
        updateBt.setEnabled(enable);
    }

    private boolean passwordMatches() {
        char[] pw = pwTx.getPassword();
        char[] conPw = conPwTx.getPassword();
        if(pw.length != conPw.length){
            return false;
        }
        
        for(int i = 0; i < pw.length; i++){
            if (pw[i] != conPw[i]) {
                return false;
            }
        }
        
        return true;
    }
    
    private void clearAll(){
        fNameTx.setText("");
        lNameTx.setText("");
        nicTx.setText("");
        mailTx.setText("");
        addressTx.setText("");
        tpTx.setText("");
        pwTx.setText("");
        conPwTx.setText("");
        profPic = null;
        profPicLb.setIcon(new ImageIcon("./src/pics/noProfPic.png"));
        createBt.setEnabled(false);
    }
}
